cosmos/awesome-cosmos

README.md

Add [https://bharvest.io/wallet_en](https://bharvest.io/wallet_en) to Block Explorers list

Add B-Harvest to explorer

---

README.md

- Section for modules to be listed and expanded on
Changes are made throughout by a markdown linter, if this needs to be changed back, let me know.
Signed-off-by: Marko Baricevic <marbar3778@yahoo.com>

Added a module section

---

README.md

Signed-off-by: Marko Baricevic <marbar3778@yahoo.com>

Added wallets to the readme.md

---

Contributing.md
README.md

- Deleted stake.id as the link is broken now
- added contributing criteria
Signed-off-by: Marko Baricevic <marbar3778@yahoo.com>

Add Contributing criteria

---

README.md

[As commented by a user on the Cosmos forums](https://forum.cosmos.network/t/atomscan-a-blockchain-explorer-for-cosmos/2398/4?u=cracklord) that they'd like to see my explorer added to the list. So, here you go.
Would be awesome to have it on this awesome list!

Add ATOMScan blockchain explorer

---

README.md

change DAO info to project info

Update cyber info

---

README.md

do you think it's good to include anyway for any kind of legacy interactions needed with amino based chains?

Update client libs

---

README.md

This is a full fledged client library that also supports bank module and can be extended to more. Check out cli / repl support

Add cosmwasm-js

---

README.md

- Add validator monitoring tool section
- Add operating system information for wallets
- Add Kadenamint to VMs
- Remove B-Harvest explorer (service terminated)

Add validator monitoring tool, update other info

---

README.md

Band Protocol Proof 
https://medium.com/bandprotocol/bandchain-wenchang-testnet-launch-f40162f2b70c
https://github.com/bandprotocol/bandchain
Wimel's Meetup & Work
https://www.meetup.com/Proof-Of-Stake-SvQ/events/270643879/
https://github.com/Colm3na/MeetupCosmos

Added Band Protocol & Wimel's work

---

README.md

- Fixed Block Explorers link and link text in contents list
- Added Virtual Machines and Ecosystem to contents list
- Fixed typo (FOundation -> Foundation)

Fixed contents and ixo typo.

---

README.md

* updated cosmwas-js to cosmjs
* added lcnem/cosmos-client-ts

Add JS Clients

---

README.md

Add SG-1 to the known validators

Add validator SG-1

---

README.md

Closes https://github.com/cosmos/awesome/issues/72
- Change comsosjs repository address to Chainapsis
- Remove Everett protocol from ecosystem

Update cosmosjs to Chainapsis

---

README.md

Wanted to get an index of a bunch of the rust projects in one place. There's some duplication eg. CosmWasm is also in the VMs section and some stuff might be listed on the tendermint awesome but seems worth having an index into all the rust projects in one place for now ...
Sorry I pushed a few of these items to master first before this PR ...

reorg rust section

---

README.md

Add Starport as library

---

README.md

Seperate blockexplorer from validators, sort both alphabetically

---

README.md

Hi, we've updated our domain for ATOMScan, would love if you could update it here :)

Update ATOMScan URL to new domain

---

README.md

https://blog.crypto.com/the-crypto-org-chain-ecosystem-grants-programme/
3. Awesome Projects Rewards Programme
The Awesome Project Rewards Programme allows community members to share and showcase their Crypto.org Chain projects. Rewards will be granted to projects that greatly benefit the community.
To be considered for this programme, the project must:
Benefit a group of or all community members
Not promote particular validators
To get involved, please refer to this page and submit your contribution accordingly.

Related: Awesome Crypto.com Chain

---

README.md

I always wondered where I could find the atom2021 initiative, now I know! Adding here so others can find their way here also

add cosmosdev/atom2021 link to related links

---

README.md

[MediBloc Limited](https://medibloc.com/en/) has built a blockchain named Panacea based on Cosmos-SDK.
- https://github.com/medibloc/panacea-core

docs: Add MediBloc to the Ecosystem chapter

---

README.md

Re-organization of the README.
Closes #50, #103, #91, #53

docs: re-organization of the page

---

LICENSE

chore: change license to cc0

---

README.md

Removed some old items and added new ones.

Update awesome list

---

README.md

add cosmology

---

README.md

Add Kujira POD

---

README.md

Add Yieldmos

---

README.md

Adds a discord faucet that is fully configurable.

Add tools: discord faucet

---

README.md

Cosmfaucet is a self-hosted faucet service for dev teams

add: cosmfaucet

---

README.md

Add pyCosmicWrap

---

README.md

Adding UpgradesWatchdog by Chihuahua

Add UpgradesWatchdog

---

README.md

Potentially useful addition: securing your smart contracts.

Add secure contracts repo.

---

README.md

Add [Cosmos Discord Bot](https://github.com/okp4/discord-bot) to the section bots.
Thanks 😊

docs: add Discord Bot for Cosmos blockchains

---

README.md

Add Cosmscan

---

README.md

feat: add terminal block explorers

---

README.md

- [IBC Anywhere](https://ibc.reece.sh/) (Has packet forward middleware support)
- [cosmos-balance-bot](https://github.com/Reecepbcups/cosmos-balance-bot) 
- [validator-stats-notifications](https://github.com/Reecepbcups/validator-stats-notifs)
- [Secret Stashh NFT Bot](https://github.com/Reecepbcups/stashh-bot)
- [DAODAO Treasury Bot](https://github.com/Reecepbcups/dao-treasury-bot)
- [Cosmos Price Bot](https://github.com/Reecepbcups/cosmos-price-bot)
- [Cosmos Cache](https://github.com/Reecepbcups/cosmos-endpoint-cache)
---
- cosmos-indexer -> interchain-indexer
- Strangelove's ibctest -> interchaintest (This is in 2 locations, is that meant to be?)

Adds Personal Tools & scripts

---

README.md

A useful tool for sending cosmos transactions

Add fx-py-sdk python client libray

---

README.md

1) added tmtop, cosmos-transactions-bot, cosmos-proposals-checker
2) replaced missed-blocks-checker with its full rewrite from scratch (I am a maintainer of both repos and I abandoned the previous one in favour of the new one)
3) removed cosmos-exporter (I am a maintainer of it and I abandoned it as well; I wrote cosmos-wallets-exporter and cosmos-validators-exporter that provide mostly the same functionality and work way better)

Add Quokka Stake tools

---

README.md

Remove Yieldmos
